'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(__dirname+'/../src/parts/07-markup-lists-and-appearance.js','utf8');
function extract(name){const start=source.indexOf('  function '+name+'('),rest=source.slice(start),end=rest.slice(4).search(/^  (?:async )?function \w+\(/m);assert.ok(start>=0);return rest.slice(0,end+4);}
function healthFixture(){const context=vm.createContext({Date:{now:()=>100000},browserAttentionSnapshot:()=>({}),watchingLogin:()=> 'stream',readStreamInfo:()=>({live:true,game:'Game',dropsEnabled:true}),streamVideoIsPlaying:()=>true,currentDrop:{game:'Game',campaignKey:'campaign',currentMinutes:0},gameNamesMatch:(a,b)=>a===b,lastStreamVerification:{channel:'stream',game:'Game',campaignKey:'campaign',proof:{campaignSupported:true}},readRoutingControllerSession:()=>({state:'earning',targetStream:'stream',targetCampaignKey:'campaign',candidateEvidence:{campaignAclMatched:true}}),ROUTING_STATES:{EARNING:'earning'},cleanText:v=>String(v||''),currentStreamTimingSnapshot:()=>({creditedProgressAt:0,creditedProgressAgeMs:0}),UNHEALTHY_STREAM_DELAYED_MS:180000,HEALTHY_STREAM_DELAYED_MS:600000,viewingIntent:{snapshot:()=>({})},DropperActiveViewing:{recoveryDiagnosis:()=>({code:'healthy'})},progressStallTimeoutMs:()=>600000,activeRewardEligibility:()=>({code:'eligible'}),hasConfirmedRewardProgress:()=>false,rewardCreditStatus:()=> 'No Twitch credit yet',briefAge:()=> '30s'});vm.runInContext(extract('streamEarningHealthSnapshot')+extract('earningConfidencePresentation'),context);return context;}
test('eligibility alone keeps a playable stream healthy but never reports verified earning',()=>{const c=healthFixture(),h=c.streamEarningHealthSnapshot();assert.equal(h.streamEligible,true);assert.equal(h.healthy,true);assert.equal(h.earningVerified,false);assert.equal(c.earningConfidencePresentation(h).label,'Eligible stream');});
test('recent matched credit proves earning, stale credit loses verified status',()=>{const c=healthFixture();c.currentDrop.currentMinutes=5;c.lastStreamVerification.proof.progressConfirmed=true;c.currentStreamTimingSnapshot=()=>({creditedProgressAt:90000,creditedProgressAgeMs:10000});let h=c.streamEarningHealthSnapshot();assert.equal(h.earningVerified,true);c.hasConfirmedRewardProgress=()=>true;assert.equal(c.earningConfidencePresentation(h).label,'Verified');c.currentStreamTimingSnapshot=()=>({creditedProgressAt:1,creditedProgressAgeMs:999999});h=c.streamEarningHealthSnapshot();assert.equal(h.earningVerified,false);assert.equal(h.streamEligible,true);});

test('System health handles selected reward and playing stream without any credit',()=>{const c=healthFixture();c.lastGqlSuccessAt=0;c.ExtraPotionsCore={suiteSitePaused:()=>false};c.recoveryNavigationState=()=>({suspended:false});vm.runInContext(extract('systemHealthSnapshot'),c);const value=c.systemHealthSnapshot();assert.equal(value.state,'waiting');assert.match(value.reason,/Twitch.*credit/i);assert.equal(value.checkedAt,null);});
