'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm');
const {loadDropperSource}=require('./load-source.cjs');const source=loadDropperSource();
function setup(){
 const now=1000000,nodes={'tdh-compact-state':{},'tdh-drop-state':{setAttribute(){}}};
 const viewing={channel:'viewer-channel',manualStream:true,paused:false,playback:'playing',changedAt:now-180000};
 const c={Date:{now:()=>now},currentDrop:{id:'reward-1',game:'Game',campaignKey:'campaign',currentMinutes:73,requiredMinutes:120,remainingMinutes:47,name:'Reward'},lastProgressAt:now-1000,lastStreamVerification:{dropId:'reward-1',at:now-1000,channel:'viewer-channel',game:'Game',campaignKey:'campaign',proof:{progressConfirmed:true}},watchingLogin:()=>viewing.channel,cleanText:v=>String(v||'').trim(),readStreamInfo:()=>({live:true,game:'Game',dropsEnabled:true}),streamVideoIsPlaying:()=>true,gameNamesMatch:(a,b)=>a===b,readRoutingControllerSession:()=>({state:'paused',targetStream:'viewer-channel',targetCampaignKey:'campaign',candidateEvidence:{}}),ROUTING_STATES:{EARNING:'earning',VERIFY_STREAM:'verify',OPEN_STREAM:'open',WAITING:'waiting',FIND_STREAM:'find'},browserAttentionSnapshot:()=>({}),viewingIntent:{snapshot:()=>viewing},FIRST_WATCH_CREDIT_GRACE_MS:90000,UNHEALTHY_STREAM_DELAYED_MS:90000,HEALTHY_STREAM_DELAYED_MS:300000,progressStallTimeoutMs:()=>360000,DropperActiveViewing:{recoveryDiagnosis:h=>({code:h.inVerificationGrace?'verification-grace':'healthy'})},ui:{shadow:{getElementById:id=>nodes[id]||null}},getToken:()=>true,dropProgressComplete:()=>false,settings:{backgroundEarning:false},watchClock:{elapsed:0},authoritativeProgressPercent:()=>61,formatClock:()=>'',lastCheckedAt:now,renderSkipStreamerControl:()=>{}};
 for(const name of ['currentStreamTimingSnapshot','streamEarningHealthSnapshot','hasConfirmedRewardProgress','syncCompactState']){const start=source.indexOf('  function '+name+'(');const end=source.indexOf('\n  function ',start+4);assert.ok(start>=0&&end>start);vm.runInNewContext(source.slice(start,end),c);}
 return {c,viewing,nodes,now};
}
test('manual credited progress shows Earning even when automatic routing is paused',()=>{const {c,nodes}=setup();assert.equal(c.streamEarningHealthSnapshot().earningVerified,true);c.syncCompactState();assert.equal(nodes['tdh-drop-state'].textContent,'Earning');});
test('routine manual-stream confirmations do not restart first-watch grace',()=>{const {c,now}=setup();assert.equal(c.currentStreamTimingSnapshot(now).inVerificationGrace,false);c.lastStreamVerification.at=now;assert.equal(c.currentStreamTimingSnapshot(now+1000).inVerificationGrace,false);});
test('paused playback and absent progress proof cannot become manual Earning',()=>{const {c,viewing,nodes}=setup();viewing.paused=true;c.syncCompactState();assert.equal(nodes['tdh-drop-state'].textContent,'Paused');viewing.paused=false;c.lastStreamVerification.proof={sessionMatched:true};assert.equal(c.streamEarningHealthSnapshot().earningVerified,false);c.syncCompactState();assert.equal(nodes['tdh-drop-state'].textContent,'Waiting');});
