'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm');const source=require('./load-source.cjs').loadDropperSource();
function fn(name){const a=source.indexOf('  function '+name+'('),b=source.indexOf('\n  function ',a+4);return source.slice(a,b);}
function fixture(patch={}){let clicks=0;const events=[];const button={disabled:false,getClientRects:()=>[{}],click:()=>clicks++};const mini={querySelector:()=>button};const video={closest:()=>mini,getBoundingClientRect:()=>({width:320,height:180})};const c={Date,settings:{restoreChannelPlayer:true},PAGE_STARTED_AT:Date.now(),playerPresentationRecovery:{attempted:false,viewerInteracted:false,lastResult:'not-needed'},location:{pathname:'/channel'},watchingLogin:()=> 'channel',document:{hidden:false,fullscreenElement:null,pictureInPictureElement:null},viewingIntent:{snapshot:()=>({paused:false})},streamVideoElement:()=>video,logActivity:(...args)=>events.push(args),...patch};vm.runInNewContext(fn('playerPresentationSnapshot')+fn('restoreChannelPlayer'),c);return {c,button,video,clicks:()=>clicks,events};}
test('initial Twitch mini-player expands once and records request without altering playback',()=>{const f=fixture();assert.equal(f.c.playerPresentationSnapshot().mode,'twitch-mini');assert.equal(f.c.restoreChannelPlayer(),true);assert.equal(f.c.restoreChannelPlayer(),false);assert.equal(f.clicks(),1);assert.equal(f.events[0][2].reason,'mini-player-on-arrival');});
test('layout recovery respects opt-out, interaction, pause, hidden tab and elapsed arrival window',()=>{for(const patch of [{settings:{restoreChannelPlayer:false}},{playerPresentationRecovery:{viewerInteracted:true}},{viewingIntent:{snapshot:()=>({paused:true})}},{document:{hidden:true}},{PAGE_STARTED_AT:Date.now()-31000}]){const f=fixture(patch);assert.equal(f.c.restoreChannelPlayer(),false);assert.equal(f.clicks(),0);}});
test('explicit restore works after arrival but never operates fullscreen, browser PiP or another route',()=>{const f=fixture({PAGE_STARTED_AT:0});assert.equal(f.c.restoreChannelPlayer(true),true);for(const patch of [{document:{fullscreenElement:{}}},{document:{pictureInPictureElement:{}}},{location:{pathname:'/directory'}},{location:{pathname:'/channel/about'}}]){const p=fixture(patch);assert.equal(p.c.restoreChannelPlayer(true),false);assert.equal(p.clicks(),0);}});
test('normal player or missing expansion control produces no unrelated clicks',()=>{const f=fixture();f.video.closest=()=>null;assert.equal(f.c.restoreChannelPlayer(),false);const g=fixture();g.button.disabled=true;assert.equal(g.c.restoreChannelPlayer(),false);assert.equal(g.c.playerPresentationRecovery.lastResult,'expand-control-unavailable');});
test('player recovery clicks only the observed control inside Twitch mini-player DOM',async t=>{const {chromium}=require('playwright');const browser=await chromium.launch();t.after(()=>browser.close());const page=await browser.newPage();await page.route('https://www.twitch.tv/**',r=>r.fulfill({body:'<button id="unrelated" aria-label="Expand Player">Other</button><div data-a-player-state="mini"><video></video><button id="restore" aria-label="Expand Player">Expand</button></div>',contentType:'text/html'}));await page.goto('https://www.twitch.tv/channel');await page.addScriptTag({content:`const settings={restoreChannelPlayer:true},PAGE_STARTED_AT=Date.now(),playerPresentationRecovery={attempted:false,viewerInteracted:false};const watchingLogin=()=> 'channel',viewingIntent={snapshot:()=>({paused:false})},streamVideoElement=()=>document.querySelector('video'),logActivity=()=>{};${fn('restoreChannelPlayer')}window.restore=restoreChannelPlayer;window.otherClicks=0;document.querySelector('#unrelated').onclick=()=>window.otherClicks++;document.querySelector('#restore').onclick=()=>document.querySelector('[data-a-player-state]').setAttribute('data-a-player-state','');`});assert.equal(await page.evaluate(()=>restore()),true);assert.equal(await page.locator('[data-a-player-state="mini"]').count(),0);assert.equal(await page.evaluate(()=>otherClicks),0);});
test('waiting explanation gives actual Twitch credit priority over delayed DOM state',()=>{const c={};vm.runInNewContext(fn('waitingExplanation'),c);assert.match(c.waitingExplanation({creditedRecently:true,paused:true},true,false),/credited progress/);assert.match(c.waitingExplanation({paused:true},true,true),/paused/);assert.match(c.waitingExplanation({},false,false),/No active reward/);});
