'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),{loadDropperSource}=require('./load-source.cjs');
const source=loadDropperSource();
function load(){let time=1000;const storage=new Map();const c={Date:{now:()=>time},Number,Array,Math,cleanText:v=>String(v||''),readSession:(key,fallback)=>storage.get(key)||fallback,writeSession:(key,value)=>storage.set(key,value),readRoutingControllerSession:()=>({failedStreams:[]}),logActivity:()=>{},setStatus:()=>{},ExtraPotionsCore:{suiteSitePaused:()=>false},storageAccountLogin:()=> 'alice',viewingIntent:{snapshot:()=>({paused:false})}};
 for(const name of ['recoveryNavigationState','recoveryNavigationAllowed','resumeRecoveryNavigation']){const match=new RegExp('  function '+name+'\\([^]*?\\n  \\}').exec(source);assert.ok(match,name);vm.runInNewContext(match[0],c);}return{c,advance:value=>time+=value};}
test('three recovery moves are allowed, the fourth suspends and manual navigation is excluded',()=>{const {c}=load();for(let i=0;i<3;i++)assert.equal(c.recoveryNavigationAllowed('campaign-stream-retry'),true);assert.equal(c.recoveryNavigationAllowed('campaign-stream-retry'),false);assert.equal(c.recoveryNavigationState().suspended,true);assert.equal(c.recoveryNavigationAllowed('manual-stream-skip'),true);c.resumeRecoveryNavigation();assert.equal(c.recoveryNavigationState().suspended,false);});
test('old pressure expires and a paused user cannot be resumed',()=>{const {c,advance}=load();c.recoveryNavigationAllowed('recovery');advance(300001);assert.equal(c.recoveryNavigationState().events.length,0);c.viewingIntent.snapshot=()=>({paused:true});assert.equal(c.resumeRecoveryNavigation(),false);});

test('blocked recovery navigation creates no flight, notification, mute or viewing intent',()=>{const {c}=load(),effects=[];for(let i=0;i<3;i++)c.recoveryNavigationAllowed('campaign-stream-retry');Object.assign(c,{URL,location:{href:'https://www.twitch.tv/first',assign:()=>effects.push('assign')},isTrustedTwitchUrl:()=>true,viewingNavigationAllowed:()=>true,isAutoRoutingController:()=>true,categorySlugFromUrl:()=>'',EXCLUDED_CATEGORY_SLUGS:new Set(),navigationLocationKey:u=>u,navigationFlightSnapshot:()=>null,navigationGuardSnapshot:()=>({events:[],blocked:false}),watchingLogin:()=> 'first',PAGE_STARTED_AT:0,STREAM_ROUTE_SETTLE_MS:100,AUTO_NAVIGATION_WINDOW_MS:60000,AUTO_NAVIGATION_LIMIT:6,AUTO_NAVIGATION_IN_FLIGHT_MS:10000,writeNavigationGuard:()=>effects.push('guard'),clearSkipStreamerArm:()=>effects.push('skip'),streamLoginFromUrl:()=> 'second',settings:{muteRestarted:true},currentDrop:{game:'Fixture'},requestMuteAfterNavigation:()=>effects.push('mute'),sendBrowserNotification:()=>effects.push('notification'),noteRequestedViewingNavigation:()=>effects.push('intent'),explicitViewingNavigationUntil:42});const write=c.writeSession;c.writeSession=(key,value)=>{if(key==='flight')effects.push('flight');write(key,value);};c.NAVIGATION_FLIGHT_KEY='flight';c.logActivity=type=>{if(type==='navigation')effects.push('navigation');};const match=/  function autoNavigateTwitch\([^]*?\n  \}/.exec(source);assert.ok(match);vm.runInNewContext(match[0],c);assert.equal(c.autoNavigateTwitch('https://www.twitch.tv/second','campaign-stream-retry'),false);assert.deepEqual(effects,[]);assert.equal(c.explicitViewingNavigationUntil,42);});
